**Task 1: Fundamentals (3 Points)**

- Create an array with a different length and two arrays of the same length after importing NumPy (3 arrays in total).
- Execute at least four different operations on arrays of the same size.
- Create four variables containing a string, integer, float, and Boolean and try to cast them to (in order) Boolean, float, integer, and string. 

In [2]:
# Create an array with a different length and two arrays of the same length after importing NumPy
import numpy as np
a = np.array([1, 2, 3, 4, 5])

# 2 arrays with same length
b = np.array([1,2,3])
c = np.array([2,3,4])


In [9]:
# Execute at least four different operations on arrays of the same size.
# addition
print (b+c)

# subtraction
print (b-c)

# multiplication
print (b*c)

# division
print (np.round((b/c),2))

[3 5 7]
[-1 -1 -1]
[ 2  6 12]
[0.5  0.67 0.75]


In [10]:
# Create four variables containing a string, integer, float, and Boolean 
# and try to cast them to (in order) Boolean, float, integer, and string.

string = "string"
integer = 1
float = 2.5
boolean = True

print (boolean)
print(float)
print(integer)
print (string)

True
2.5
1
string


**Task 2: Control Flow (2 Points)**

Create an array containing the first 10 letters of the alphabet. 
Iterate through the array using a for loop. 
Inside the for loop, use an if statement to print the word "four" instead of the letter "d" and "eight" instead of the letter "i", otherwise print the alphabet letter.

In [11]:
# Create an array containing the first 10 letters of the alphabet. 
array = np.array(['a','b','c','d','e','f','g','h','i','j'])

for alphabet in array:
    if alphabet == 'd':
        print ("four")
    elif alphabet == 'i':
        print ("eight")
    else:
        print (alphabet)

a
b
c
four
e
f
g
h
eight
j


**Task 3: Data Structure (2 Points)**

- Create a tuple containing 4 strings and a list containing 7 strings. Unpack the tuple into 4 different variables and print them. Then try to remove an element from the list and instead insert one of the variables that were the result of unpacking the tuple. Finally, slice and sort the last 3 elements of the list.
  
- Create a dictionary with these keys: 'numbers', 'letters', 'words', 'sentences', 'dates', 'times' and 'months' and for each key, assign a value of that specific type. For instance, you should create a temporary small list to assign to the 'numbers' key, a temporary small string to assign to the 'sentences' key, and a temporary small tuple to assign to the 'dates' key.


In [24]:
# Create a tuple containing 4 strings and a list containing 7 strings. 
cities = ("NewYork", "Chicago", "Boston", "Miami")
animals = ["Snake", "Elephant", "Tiger", "Zebra", "Giraffe", "Monkey", "Bear"]

# Unpack the tuple into 4 different variables and print them.
(NewYork, Chicago, Boston, Miami) = cities
print (cities)

('NewYork', 'Chicago', 'Boston', 'Miami')


In [25]:
# Then try to remove an element from the list 
animals.remove("Bear")
print (animals)

# and instead insert one of the variables that were the result of unpacking the tuple
animals.append(cities[0])
print (animals)

['Snake', 'Elephant', 'Tiger', 'Zebra', 'Giraffe', 'Monkey']
['Snake', 'Elephant', 'Tiger', 'Zebra', 'Giraffe', 'Monkey', 'NewYork']


In [28]:
# Finally, slice and sort the last 3 elements of the list.
sliced = animals[-3:]
print(sorted(sliced))

['Giraffe', 'Monkey', 'NewYork']


In [29]:
# Create a dictionary with these keys: 'numbers', 'letters', 'words', 'sentences', 'dates', 'times' and 'months' 
# for each key, assign a value of that specific type.
temp_number = [1,2,3,4]
temp_letters = ['a','b','c','d']
temp_words = ['NewYork', 'Chicago', 'Boston', 'Miami']
temp_sentences = "This is a sentence."
temp_dates = ("2026-01-01", "2026-01-02")
temp_times = ["07:00", "08:00", "09:00"]
temp_months = ("January", "February", "March")


data = {
    'numbers': temp_number,
    'letters': temp_letters,
    'words': temp_words,
    'sentences': temp_sentences, 
    'dates': temp_dates,
    'times': temp_times,
    'months': temp_months
}

print(data)

{'numbers': [1, 2, 3, 4], 'letters': ['a', 'b', 'c', 'd'], 'words': ['NewYork', 'Chicago', 'Boston', 'Miami'], 'sentences': 'This is a sentence.', 'dates': ('2026-01-01', '2026-01-02'), 'times': ['07:00', '08:00', '09:00'], 'months': ('January', 'February', 'March')}


**Task 4: Sequence Function (3 Points)**

Create a list containing numbers from 11 to 16, then using a for loop and proper indexing, produce the following output:
12 --> 11

13 --> 12

14 --> 13

15 --> 14

16 --> 15

17 --> 16

In [37]:
# Create a list containing numbers from 11 to 16,
numbers = [11, 12, 13, 14, 15, 16]

# Create a new list with the “shifted” numbers on the left
new_list = [12, 13, 14, 15, 16, 17]

# zip new list and numbers together
for left, right in zip(new_list, numbers):
    print(f"{left} --> {right}")

12 --> 11
13 --> 12
14 --> 13
15 --> 14
16 --> 15
17 --> 16


**Task 5: Copying (2 Points)**

By copying the previous list, create a new variable containing the same numbers from 11 to 16 elements from the previous list. Change an element in one of the variables and make sure the other doesn't change.

In [38]:
# previous list
numbers = [11, 12, 13, 14, 15, 16]

# new variable
new_variable = numbers.copy()

# change an element
new_variable[0] = 200

print (new_variable)
print (numbers)

[200, 12, 13, 14, 15, 16]
[11, 12, 13, 14, 15, 16]


**Task 6: Exception Handling (2 Points)**

Create a variable containing a tuple object. Then try to change its first element the way you change an element in a list and see what kind of error you will get. Then try to catch handle the error and instead of the error print "Tuples are immutable :)" 

In [39]:
# Create a variable containing a tuple object. 
tuple_test = (1, 2, 3, 4, 5)

# try to change its first element 
tuple_test[0] = 100
print (tuple_test)

TypeError: 'tuple' object does not support item assignment

In [41]:
try:
    tuple_test = (1, 2, 3, 4, 5)
    tuple_test[0] = 100
    print (tuple_test)

except TypeError:
    print ("Tuples are immutable :)")

Tuples are immutable :)
